// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnc9RerIu74dWSpkXRsVxqna--VxCzG1Y',
    appId: '1:357984365786:web:0ecff814e17f92285389e3',
    messagingSenderId: '357984365786',
    projectId: 'dawwerha-71e20',
    authDomain: 'dawwerha-71e20.firebaseapp.com',
    storageBucket: 'dawwerha-71e20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiBksejZDfZiHjPpZPoK9x4Ju3NxwZKfE',
    appId: '1:357984365786:android:80b134cdc93ebe595389e3',
    messagingSenderId: '357984365786',
    projectId: 'dawwerha-71e20',
    storageBucket: 'dawwerha-71e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSiaqsDDI05Hx8kjP9Xqj9e_beBmnj4TY',
    appId: '1:357984365786:ios:00f2c7b940ca78ed5389e3',
    messagingSenderId: '357984365786',
    projectId: 'dawwerha-71e20',
    storageBucket: 'dawwerha-71e20.firebasestorage.app',
    iosBundleId: 'com.example.dawwerha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSiaqsDDI05Hx8kjP9Xqj9e_beBmnj4TY',
    appId: '1:357984365786:ios:00f2c7b940ca78ed5389e3',
    messagingSenderId: '357984365786',
    projectId: 'dawwerha-71e20',
    storageBucket: 'dawwerha-71e20.firebasestorage.app',
    iosBundleId: 'com.example.dawwerha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnc9RerIu74dWSpkXRsVxqna--VxCzG1Y',
    appId: '1:357984365786:web:3930806b7d1f19745389e3',
    messagingSenderId: '357984365786',
    projectId: 'dawwerha-71e20',
    authDomain: 'dawwerha-71e20.firebaseapp.com',
    storageBucket: 'dawwerha-71e20.firebasestorage.app',
  );
}
